// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/cached_content.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Content that has been preprocessed and can be used in subsequent request
/// to GenerativeService.
///
/// Cached content can be only used with model it was created for.
public struct Google_Ai_Generativelanguage_V1beta_CachedContent: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Specifies when this resource will expire.
  public var expiration: OneOf_Expiration? {
    get {return _storage._expiration}
    set {_uniqueStorage()._expiration = newValue}
  }

  /// Timestamp in UTC of when this resource is considered expired.
  /// This is *always* provided on output, regardless of what was sent
  /// on input.
  public var expireTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .expireTime(let v)? = _storage._expiration {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {_uniqueStorage()._expiration = .expireTime(newValue)}
  }

  /// Input only. New TTL for this resource, input only.
  public var ttl: SwiftProtobuf.Google_Protobuf_Duration {
    get {
      if case .ttl(let v)? = _storage._expiration {return v}
      return SwiftProtobuf.Google_Protobuf_Duration()
    }
    set {_uniqueStorage()._expiration = .ttl(newValue)}
  }

  /// Output only. Identifier. The resource name referring to the cached content.
  /// Format: `cachedContents/{id}`
  public var name: String {
    get {_storage._name ?? String()}
    set {_uniqueStorage()._name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  public var hasName: Bool {_storage._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  public mutating func clearName() {_uniqueStorage()._name = nil}

  /// Optional. Immutable. The user-generated meaningful display name of the
  /// cached content. Maximum 128 Unicode characters.
  public var displayName: String {
    get {_storage._displayName ?? String()}
    set {_uniqueStorage()._displayName = newValue}
  }
  /// Returns true if `displayName` has been explicitly set.
  public var hasDisplayName: Bool {_storage._displayName != nil}
  /// Clears the value of `displayName`. Subsequent reads from it will return its default value.
  public mutating func clearDisplayName() {_uniqueStorage()._displayName = nil}

  /// Required. Immutable. The name of the `Model` to use for cached content
  /// Format: `models/{model}`
  public var model: String {
    get {_storage._model ?? String()}
    set {_uniqueStorage()._model = newValue}
  }
  /// Returns true if `model` has been explicitly set.
  public var hasModel: Bool {_storage._model != nil}
  /// Clears the value of `model`. Subsequent reads from it will return its default value.
  public mutating func clearModel() {_uniqueStorage()._model = nil}

  /// Optional. Input only. Immutable. Developer set system instruction.
  /// Currently text only.
  public var systemInstruction: Google_Ai_Generativelanguage_V1beta_Content {
    get {_storage._systemInstruction ?? Google_Ai_Generativelanguage_V1beta_Content()}
    set {_uniqueStorage()._systemInstruction = newValue}
  }
  /// Returns true if `systemInstruction` has been explicitly set.
  public var hasSystemInstruction: Bool {_storage._systemInstruction != nil}
  /// Clears the value of `systemInstruction`. Subsequent reads from it will return its default value.
  public mutating func clearSystemInstruction() {_uniqueStorage()._systemInstruction = nil}

  /// Optional. Input only. Immutable. The content to cache.
  public var contents: [Google_Ai_Generativelanguage_V1beta_Content] {
    get {_storage._contents}
    set {_uniqueStorage()._contents = newValue}
  }

  /// Optional. Input only. Immutable. A list of `Tools` the model may use to
  /// generate the next response
  public var tools: [Google_Ai_Generativelanguage_V1beta_Tool] {
    get {_storage._tools}
    set {_uniqueStorage()._tools = newValue}
  }

  /// Optional. Input only. Immutable. Tool config. This config is shared for all
  /// tools.
  public var toolConfig: Google_Ai_Generativelanguage_V1beta_ToolConfig {
    get {_storage._toolConfig ?? Google_Ai_Generativelanguage_V1beta_ToolConfig()}
    set {_uniqueStorage()._toolConfig = newValue}
  }
  /// Returns true if `toolConfig` has been explicitly set.
  public var hasToolConfig: Bool {_storage._toolConfig != nil}
  /// Clears the value of `toolConfig`. Subsequent reads from it will return its default value.
  public mutating func clearToolConfig() {_uniqueStorage()._toolConfig = nil}

  /// Output only. Creation time of the cache entry.
  public var createTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._createTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._createTime = newValue}
  }
  /// Returns true if `createTime` has been explicitly set.
  public var hasCreateTime: Bool {_storage._createTime != nil}
  /// Clears the value of `createTime`. Subsequent reads from it will return its default value.
  public mutating func clearCreateTime() {_uniqueStorage()._createTime = nil}

  /// Output only. When the cache entry was last updated in UTC time.
  public var updateTime: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._updateTime ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._updateTime = newValue}
  }
  /// Returns true if `updateTime` has been explicitly set.
  public var hasUpdateTime: Bool {_storage._updateTime != nil}
  /// Clears the value of `updateTime`. Subsequent reads from it will return its default value.
  public mutating func clearUpdateTime() {_uniqueStorage()._updateTime = nil}

  /// Output only. Metadata on the usage of the cached content.
  public var usageMetadata: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata {
    get {_storage._usageMetadata ?? Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata()}
    set {_uniqueStorage()._usageMetadata = newValue}
  }
  /// Returns true if `usageMetadata` has been explicitly set.
  public var hasUsageMetadata: Bool {_storage._usageMetadata != nil}
  /// Clears the value of `usageMetadata`. Subsequent reads from it will return its default value.
  public mutating func clearUsageMetadata() {_uniqueStorage()._usageMetadata = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Specifies when this resource will expire.
  public enum OneOf_Expiration: Equatable, Sendable {
    /// Timestamp in UTC of when this resource is considered expired.
    /// This is *always* provided on output, regardless of what was sent
    /// on input.
    case expireTime(SwiftProtobuf.Google_Protobuf_Timestamp)
    /// Input only. New TTL for this resource, input only.
    case ttl(SwiftProtobuf.Google_Protobuf_Duration)

  }

  /// Metadata on the usage of the cached content.
  public struct UsageMetadata: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    /// Total number of tokens that the cached content consumes.
    public var totalTokenCount: Int32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_CachedContent: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CachedContent"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}model\0\u{3}system_instruction\0\u{1}contents\0\u{1}tools\0\u{3}tool_config\0\u{3}create_time\0\u{3}update_time\0\u{3}expire_time\0\u{1}ttl\0\u{3}display_name\0\u{3}usage_metadata\0")

  fileprivate class _StorageClass {
    var _expiration: Google_Ai_Generativelanguage_V1beta_CachedContent.OneOf_Expiration?
    var _name: String? = nil
    var _displayName: String? = nil
    var _model: String? = nil
    var _systemInstruction: Google_Ai_Generativelanguage_V1beta_Content? = nil
    var _contents: [Google_Ai_Generativelanguage_V1beta_Content] = []
    var _tools: [Google_Ai_Generativelanguage_V1beta_Tool] = []
    var _toolConfig: Google_Ai_Generativelanguage_V1beta_ToolConfig? = nil
    var _createTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _updateTime: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _usageMetadata: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _expiration = source._expiration
      _name = source._name
      _displayName = source._displayName
      _model = source._model
      _systemInstruction = source._systemInstruction
      _contents = source._contents
      _tools = source._tools
      _toolConfig = source._toolConfig
      _createTime = source._createTime
      _updateTime = source._updateTime
      _usageMetadata = source._usageMetadata
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._model) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._systemInstruction) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._contents) }()
        case 5: try { try decoder.decodeRepeatedMessageField(value: &_storage._tools) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._toolConfig) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._createTime) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._updateTime) }()
        case 9: try {
          var v: SwiftProtobuf.Google_Protobuf_Timestamp?
          var hadOneofValue = false
          if let current = _storage._expiration {
            hadOneofValue = true
            if case .expireTime(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._expiration = .expireTime(v)
          }
        }()
        case 10: try {
          var v: SwiftProtobuf.Google_Protobuf_Duration?
          var hadOneofValue = false
          if let current = _storage._expiration {
            hadOneofValue = true
            if case .ttl(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._expiration = .ttl(v)
          }
        }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._displayName) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._usageMetadata) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._name {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._model {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._systemInstruction {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._contents.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._contents, fieldNumber: 4)
      }
      if !_storage._tools.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._tools, fieldNumber: 5)
      }
      try { if let v = _storage._toolConfig {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._createTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._updateTime {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      switch _storage._expiration {
      case .expireTime?: try {
        guard case .expireTime(let v)? = _storage._expiration else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      }()
      case .ttl?: try {
        guard case .ttl(let v)? = _storage._expiration else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      }()
      case nil: break
      }
      try { if let v = _storage._displayName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._usageMetadata {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CachedContent, rhs: Google_Ai_Generativelanguage_V1beta_CachedContent) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._expiration != rhs_storage._expiration {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._displayName != rhs_storage._displayName {return false}
        if _storage._model != rhs_storage._model {return false}
        if _storage._systemInstruction != rhs_storage._systemInstruction {return false}
        if _storage._contents != rhs_storage._contents {return false}
        if _storage._tools != rhs_storage._tools {return false}
        if _storage._toolConfig != rhs_storage._toolConfig {return false}
        if _storage._createTime != rhs_storage._createTime {return false}
        if _storage._updateTime != rhs_storage._updateTime {return false}
        if _storage._usageMetadata != rhs_storage._usageMetadata {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Google_Ai_Generativelanguage_V1beta_CachedContent.protoMessageName + ".UsageMetadata"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}total_token_count\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.totalTokenCount) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.totalTokenCount != 0 {
      try visitor.visitSingularInt32Field(value: self.totalTokenCount, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata, rhs: Google_Ai_Generativelanguage_V1beta_CachedContent.UsageMetadata) -> Bool {
    if lhs.totalTokenCount != rhs.totalTokenCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
