// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/safety.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// The category of a rating.
///
/// These categories cover various kinds of harms that developers
/// may wish to adjust.
enum Google_Ai_Generativelanguage_V1beta_HarmCategory: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int

  /// Category is unspecified.
  case unspecified // = 0

  /// **PaLM** - Negative or harmful comments targeting identity and/or protected
  /// attribute.
  case derogatory // = 1

  /// **PaLM** - Content that is rude, disrespectful, or profane.
  case toxicity // = 2

  /// **PaLM** - Describes scenarios depicting violence against an individual or
  /// group, or general descriptions of gore.
  case violence // = 3

  /// **PaLM** - Contains references to sexual acts or other lewd content.
  case sexual // = 4

  /// **PaLM** - Promotes unchecked medical advice.
  case medical // = 5

  /// **PaLM** - Dangerous content that promotes, facilitates, or encourages
  /// harmful acts.
  case dangerous // = 6

  /// **Gemini** - Harassment content.
  case harassment // = 7

  /// **Gemini** - Hate speech and content.
  case hateSpeech // = 8

  /// **Gemini** - Sexually explicit content.
  case sexuallyExplicit // = 9

  /// **Gemini** - Dangerous content.
  case dangerousContent // = 10

  /// **Gemini** - Content that may be used to harm civic integrity.
  /// DEPRECATED: use enable_enhanced_civic_answers instead.
  ///
  /// NOTE: This enum value was marked as deprecated in the .proto file
  case civicIntegrity // = 11
  case UNRECOGNIZED(Int)

  init() {
    self = .unspecified
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .derogatory
    case 2: self = .toxicity
    case 3: self = .violence
    case 4: self = .sexual
    case 5: self = .medical
    case 6: self = .dangerous
    case 7: self = .harassment
    case 8: self = .hateSpeech
    case 9: self = .sexuallyExplicit
    case 10: self = .dangerousContent
    case 11: self = .civicIntegrity
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .derogatory: return 1
    case .toxicity: return 2
    case .violence: return 3
    case .sexual: return 4
    case .medical: return 5
    case .dangerous: return 6
    case .harassment: return 7
    case .hateSpeech: return 8
    case .sexuallyExplicit: return 9
    case .dangerousContent: return 10
    case .civicIntegrity: return 11
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Google_Ai_Generativelanguage_V1beta_HarmCategory] = [
    .unspecified,
    .derogatory,
    .toxicity,
    .violence,
    .sexual,
    .medical,
    .dangerous,
    .harassment,
    .hateSpeech,
    .sexuallyExplicit,
    .dangerousContent,
    .civicIntegrity,
  ]

}

/// Content filtering metadata associated with processing a single request.
///
/// ContentFilter contains a reason and an optional supporting string. The reason
/// may be unspecified.
struct Google_Ai_Generativelanguage_V1beta_ContentFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The reason content was blocked during request processing.
  var reason: Google_Ai_Generativelanguage_V1beta_ContentFilter.BlockedReason = .unspecified

  /// A string that describes the filtering behavior in more detail.
  var message: String {
    get {_message ?? String()}
    set {_message = newValue}
  }
  /// Returns true if `message` has been explicitly set.
  var hasMessage: Bool {self._message != nil}
  /// Clears the value of `message`. Subsequent reads from it will return its default value.
  mutating func clearMessage() {self._message = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// A list of reasons why content may have been blocked.
  enum BlockedReason: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// A blocked reason was not specified.
    case unspecified // = 0

    /// Content was blocked by safety settings.
    case safety // = 1

    /// Content was blocked, but the reason is uncategorized.
    case other // = 2
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .safety
      case 2: self = .other
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .safety: return 1
      case .other: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Google_Ai_Generativelanguage_V1beta_ContentFilter.BlockedReason] = [
      .unspecified,
      .safety,
      .other,
    ]

  }

  init() {}

  fileprivate var _message: String? = nil
}

/// Safety feedback for an entire request.
///
/// This field is populated if content in the input and/or response is blocked
/// due to safety settings. SafetyFeedback may not exist for every HarmCategory.
/// Each SafetyFeedback will return the safety settings used by the request as
/// well as the lowest HarmProbability that should be allowed in order to return
/// a result.
struct Google_Ai_Generativelanguage_V1beta_SafetyFeedback: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Safety rating evaluated from content.
  var rating: Google_Ai_Generativelanguage_V1beta_SafetyRating {
    get {_rating ?? Google_Ai_Generativelanguage_V1beta_SafetyRating()}
    set {_rating = newValue}
  }
  /// Returns true if `rating` has been explicitly set.
  var hasRating: Bool {self._rating != nil}
  /// Clears the value of `rating`. Subsequent reads from it will return its default value.
  mutating func clearRating() {self._rating = nil}

  /// Safety settings applied to the request.
  var setting: Google_Ai_Generativelanguage_V1beta_SafetySetting {
    get {_setting ?? Google_Ai_Generativelanguage_V1beta_SafetySetting()}
    set {_setting = newValue}
  }
  /// Returns true if `setting` has been explicitly set.
  var hasSetting: Bool {self._setting != nil}
  /// Clears the value of `setting`. Subsequent reads from it will return its default value.
  mutating func clearSetting() {self._setting = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _rating: Google_Ai_Generativelanguage_V1beta_SafetyRating? = nil
  fileprivate var _setting: Google_Ai_Generativelanguage_V1beta_SafetySetting? = nil
}

/// Safety rating for a piece of content.
///
/// The safety rating contains the category of harm and the
/// harm probability level in that category for a piece of content.
/// Content is classified for safety across a number of
/// harm categories and the probability of the harm classification is included
/// here.
struct Google_Ai_Generativelanguage_V1beta_SafetyRating: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The category for this rating.
  var category: Google_Ai_Generativelanguage_V1beta_HarmCategory = .unspecified

  /// Required. The probability of harm for this content.
  var probability: Google_Ai_Generativelanguage_V1beta_SafetyRating.HarmProbability = .unspecified

  /// Was this content blocked because of this rating?
  var blocked: Bool = false

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// The probability that a piece of content is harmful.
  ///
  /// The classification system gives the probability of the content being
  /// unsafe. This does not indicate the severity of harm for a piece of content.
  enum HarmProbability: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// Probability is unspecified.
    case unspecified // = 0

    /// Content has a negligible chance of being unsafe.
    case negligible // = 1

    /// Content has a low chance of being unsafe.
    case low // = 2

    /// Content has a medium chance of being unsafe.
    case medium // = 3

    /// Content has a high chance of being unsafe.
    case high // = 4
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .negligible
      case 2: self = .low
      case 3: self = .medium
      case 4: self = .high
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .negligible: return 1
      case .low: return 2
      case .medium: return 3
      case .high: return 4
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Google_Ai_Generativelanguage_V1beta_SafetyRating.HarmProbability] = [
      .unspecified,
      .negligible,
      .low,
      .medium,
      .high,
    ]

  }

  init() {}
}

/// Safety setting, affecting the safety-blocking behavior.
///
/// Passing a safety setting for a category changes the allowed probability that
/// content is blocked.
struct Google_Ai_Generativelanguage_V1beta_SafetySetting: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The category for this setting.
  var category: Google_Ai_Generativelanguage_V1beta_HarmCategory = .unspecified

  /// Required. Controls the probability threshold at which harm is blocked.
  var threshold: Google_Ai_Generativelanguage_V1beta_SafetySetting.HarmBlockThreshold = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Block at and beyond a specified harm probability.
  enum HarmBlockThreshold: SwiftProtobuf.Enum, Swift.CaseIterable {
    typealias RawValue = Int

    /// Threshold is unspecified.
    case unspecified // = 0

    /// Content with NEGLIGIBLE will be allowed.
    case blockLowAndAbove // = 1

    /// Content with NEGLIGIBLE and LOW will be allowed.
    case blockMediumAndAbove // = 2

    /// Content with NEGLIGIBLE, LOW, and MEDIUM will be allowed.
    case blockOnlyHigh // = 3

    /// All content will be allowed.
    case blockNone // = 4

    /// Turn off the safety filter.
    case off // = 5
    case UNRECOGNIZED(Int)

    init() {
      self = .unspecified
    }

    init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .unspecified
      case 1: self = .blockLowAndAbove
      case 2: self = .blockMediumAndAbove
      case 3: self = .blockOnlyHigh
      case 4: self = .blockNone
      case 5: self = .off
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    var rawValue: Int {
      switch self {
      case .unspecified: return 0
      case .blockLowAndAbove: return 1
      case .blockMediumAndAbove: return 2
      case .blockOnlyHigh: return 3
      case .blockNone: return 4
      case .off: return 5
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    static let allCases: [Google_Ai_Generativelanguage_V1beta_SafetySetting.HarmBlockThreshold] = [
      .unspecified,
      .blockLowAndAbove,
      .blockMediumAndAbove,
      .blockOnlyHigh,
      .blockNone,
      .off,
    ]

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_HarmCategory: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HARM_CATEGORY_UNSPECIFIED\0\u{1}HARM_CATEGORY_DEROGATORY\0\u{1}HARM_CATEGORY_TOXICITY\0\u{1}HARM_CATEGORY_VIOLENCE\0\u{1}HARM_CATEGORY_SEXUAL\0\u{1}HARM_CATEGORY_MEDICAL\0\u{1}HARM_CATEGORY_DANGEROUS\0\u{1}HARM_CATEGORY_HARASSMENT\0\u{1}HARM_CATEGORY_HATE_SPEECH\0\u{1}HARM_CATEGORY_SEXUALLY_EXPLICIT\0\u{1}HARM_CATEGORY_DANGEROUS_CONTENT\0\u{1}HARM_CATEGORY_CIVIC_INTEGRITY\0")
}

extension Google_Ai_Generativelanguage_V1beta_ContentFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ContentFilter"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reason\0\u{1}message\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.reason) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._message) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.reason != .unspecified {
      try visitor.visitSingularEnumField(value: self.reason, fieldNumber: 1)
    }
    try { if let v = self._message {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_ContentFilter, rhs: Google_Ai_Generativelanguage_V1beta_ContentFilter) -> Bool {
    if lhs.reason != rhs.reason {return false}
    if lhs._message != rhs._message {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_ContentFilter.BlockedReason: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BLOCKED_REASON_UNSPECIFIED\0\u{1}SAFETY\0\u{1}OTHER\0")
}

extension Google_Ai_Generativelanguage_V1beta_SafetyFeedback: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SafetyFeedback"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rating\0\u{1}setting\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._rating) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._setting) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rating {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._setting {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_SafetyFeedback, rhs: Google_Ai_Generativelanguage_V1beta_SafetyFeedback) -> Bool {
    if lhs._rating != rhs._rating {return false}
    if lhs._setting != rhs._setting {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_SafetyRating: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SafetyRating"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}category\0\u{1}probability\0\u{1}blocked\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularEnumField(value: &self.category) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.probability) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.blocked) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.category != .unspecified {
      try visitor.visitSingularEnumField(value: self.category, fieldNumber: 3)
    }
    if self.probability != .unspecified {
      try visitor.visitSingularEnumField(value: self.probability, fieldNumber: 4)
    }
    if self.blocked != false {
      try visitor.visitSingularBoolField(value: self.blocked, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_SafetyRating, rhs: Google_Ai_Generativelanguage_V1beta_SafetyRating) -> Bool {
    if lhs.category != rhs.category {return false}
    if lhs.probability != rhs.probability {return false}
    if lhs.blocked != rhs.blocked {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_SafetyRating.HarmProbability: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HARM_PROBABILITY_UNSPECIFIED\0\u{1}NEGLIGIBLE\0\u{1}LOW\0\u{1}MEDIUM\0\u{1}HIGH\0")
}

extension Google_Ai_Generativelanguage_V1beta_SafetySetting: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".SafetySetting"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{3}category\0\u{1}threshold\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 3: try { try decoder.decodeSingularEnumField(value: &self.category) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.threshold) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.category != .unspecified {
      try visitor.visitSingularEnumField(value: self.category, fieldNumber: 3)
    }
    if self.threshold != .unspecified {
      try visitor.visitSingularEnumField(value: self.threshold, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_SafetySetting, rhs: Google_Ai_Generativelanguage_V1beta_SafetySetting) -> Bool {
    if lhs.category != rhs.category {return false}
    if lhs.threshold != rhs.threshold {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_SafetySetting.HarmBlockThreshold: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0HARM_BLOCK_THRESHOLD_UNSPECIFIED\0\u{1}BLOCK_LOW_AND_ABOVE\0\u{1}BLOCK_MEDIUM_AND_ABOVE\0\u{1}BLOCK_ONLY_HIGH\0\u{1}BLOCK_NONE\0\u{1}OFF\0")
}
