// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: google/ai/generativelanguage/v1beta/text_service.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Request to generate a text completion response from the model.
struct Google_Ai_Generativelanguage_V1beta_GenerateTextRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The name of the `Model` or `TunedModel` to use for generating the
  /// completion.
  /// Examples:
  ///  models/text-bison-001
  ///  tunedModels/sentence-translator-u3b7m
  var model: String = String()

  /// Required. The free-form input text given to the model as a prompt.
  ///
  /// Given a prompt, the model will generate a TextCompletion response it
  /// predicts as the completion of the input text.
  var prompt: Google_Ai_Generativelanguage_V1beta_TextPrompt {
    get {_prompt ?? Google_Ai_Generativelanguage_V1beta_TextPrompt()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  mutating func clearPrompt() {self._prompt = nil}

  /// Optional. Controls the randomness of the output.
  /// Note: The default value varies by model, see the `Model.temperature`
  /// attribute of the `Model` returned the `getModel` function.
  ///
  /// Values can range from [0.0,1.0],
  /// inclusive. A value closer to 1.0 will produce responses that are more
  /// varied and creative, while a value closer to 0.0 will typically result in
  /// more straightforward responses from the model.
  var temperature: Float {
    get {_temperature ?? 0}
    set {_temperature = newValue}
  }
  /// Returns true if `temperature` has been explicitly set.
  var hasTemperature: Bool {self._temperature != nil}
  /// Clears the value of `temperature`. Subsequent reads from it will return its default value.
  mutating func clearTemperature() {self._temperature = nil}

  /// Optional. Number of generated responses to return.
  ///
  /// This value must be between [1, 8], inclusive. If unset, this will default
  /// to 1.
  var candidateCount: Int32 {
    get {_candidateCount ?? 0}
    set {_candidateCount = newValue}
  }
  /// Returns true if `candidateCount` has been explicitly set.
  var hasCandidateCount: Bool {self._candidateCount != nil}
  /// Clears the value of `candidateCount`. Subsequent reads from it will return its default value.
  mutating func clearCandidateCount() {self._candidateCount = nil}

  /// Optional. The maximum number of tokens to include in a candidate.
  ///
  /// If unset, this will default to output_token_limit specified in the `Model`
  /// specification.
  var maxOutputTokens: Int32 {
    get {_maxOutputTokens ?? 0}
    set {_maxOutputTokens = newValue}
  }
  /// Returns true if `maxOutputTokens` has been explicitly set.
  var hasMaxOutputTokens: Bool {self._maxOutputTokens != nil}
  /// Clears the value of `maxOutputTokens`. Subsequent reads from it will return its default value.
  mutating func clearMaxOutputTokens() {self._maxOutputTokens = nil}

  /// Optional. The maximum cumulative probability of tokens to consider when
  /// sampling.
  ///
  /// The model uses combined Top-k and nucleus sampling.
  ///
  /// Tokens are sorted based on their assigned probabilities so that only the
  /// most likely tokens are considered. Top-k sampling directly limits the
  /// maximum number of tokens to consider, while Nucleus sampling limits number
  /// of tokens based on the cumulative probability.
  ///
  /// Note: The default value varies by model, see the `Model.top_p`
  /// attribute of the `Model` returned the `getModel` function.
  var topP: Float {
    get {_topP ?? 0}
    set {_topP = newValue}
  }
  /// Returns true if `topP` has been explicitly set.
  var hasTopP: Bool {self._topP != nil}
  /// Clears the value of `topP`. Subsequent reads from it will return its default value.
  mutating func clearTopP() {self._topP = nil}

  /// Optional. The maximum number of tokens to consider when sampling.
  ///
  /// The model uses combined Top-k and nucleus sampling.
  ///
  /// Top-k sampling considers the set of `top_k` most probable tokens.
  /// Defaults to 40.
  ///
  /// Note: The default value varies by model, see the `Model.top_k`
  /// attribute of the `Model` returned the `getModel` function.
  var topK: Int32 {
    get {_topK ?? 0}
    set {_topK = newValue}
  }
  /// Returns true if `topK` has been explicitly set.
  var hasTopK: Bool {self._topK != nil}
  /// Clears the value of `topK`. Subsequent reads from it will return its default value.
  mutating func clearTopK() {self._topK = nil}

  /// Optional. A list of unique `SafetySetting` instances for blocking unsafe
  /// content.
  ///
  /// that will be enforced on the `GenerateTextRequest.prompt` and
  /// `GenerateTextResponse.candidates`. There should not be more than one
  /// setting for each `SafetyCategory` type. The API will block any prompts and
  /// responses that fail to meet the thresholds set by these settings. This list
  /// overrides the default settings for each `SafetyCategory` specified in the
  /// safety_settings. If there is no `SafetySetting` for a given
  /// `SafetyCategory` provided in the list, the API will use the default safety
  /// setting for that category. Harm categories HARM_CATEGORY_DEROGATORY,
  /// HARM_CATEGORY_TOXICITY, HARM_CATEGORY_VIOLENCE, HARM_CATEGORY_SEXUAL,
  /// HARM_CATEGORY_MEDICAL, HARM_CATEGORY_DANGEROUS are supported in text
  /// service.
  var safetySettings: [Google_Ai_Generativelanguage_V1beta_SafetySetting] = []

  /// The set of character sequences (up to 5) that will stop output generation.
  /// If specified, the API will stop at the first appearance of a stop
  /// sequence. The stop sequence will not be included as part of the response.
  var stopSequences: [String] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _prompt: Google_Ai_Generativelanguage_V1beta_TextPrompt? = nil
  fileprivate var _temperature: Float? = nil
  fileprivate var _candidateCount: Int32? = nil
  fileprivate var _maxOutputTokens: Int32? = nil
  fileprivate var _topP: Float? = nil
  fileprivate var _topK: Int32? = nil
}

/// The response from the model, including candidate completions.
struct Google_Ai_Generativelanguage_V1beta_GenerateTextResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Candidate responses from the model.
  var candidates: [Google_Ai_Generativelanguage_V1beta_TextCompletion] = []

  /// A set of content filtering metadata for the prompt and response
  /// text.
  ///
  /// This indicates which `SafetyCategory`(s) blocked a
  /// candidate from this response, the lowest `HarmProbability`
  /// that triggered a block, and the HarmThreshold setting for that category.
  /// This indicates the smallest change to the `SafetySettings` that would be
  /// necessary to unblock at least 1 response.
  ///
  /// The blocking is configured by the `SafetySettings` in the request (or the
  /// default `SafetySettings` of the API).
  var filters: [Google_Ai_Generativelanguage_V1beta_ContentFilter] = []

  /// Returns any safety feedback related to content filtering.
  var safetyFeedback: [Google_Ai_Generativelanguage_V1beta_SafetyFeedback] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Text given to the model as a prompt.
///
/// The Model will use this TextPrompt to Generate a text completion.
struct Google_Ai_Generativelanguage_V1beta_TextPrompt: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The prompt text.
  var text: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Output text returned from a model.
struct Google_Ai_Generativelanguage_V1beta_TextCompletion: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Output only. The generated text returned from the model.
  var output: String = String()

  /// Ratings for the safety of a response.
  ///
  /// There is at most one rating per category.
  var safetyRatings: [Google_Ai_Generativelanguage_V1beta_SafetyRating] = []

  /// Output only. Citation information for model-generated `output` in this
  /// `TextCompletion`.
  ///
  /// This field may be populated with attribution information for any text
  /// included in the `output`.
  var citationMetadata: Google_Ai_Generativelanguage_V1beta_CitationMetadata {
    get {_citationMetadata ?? Google_Ai_Generativelanguage_V1beta_CitationMetadata()}
    set {_citationMetadata = newValue}
  }
  /// Returns true if `citationMetadata` has been explicitly set.
  var hasCitationMetadata: Bool {self._citationMetadata != nil}
  /// Clears the value of `citationMetadata`. Subsequent reads from it will return its default value.
  mutating func clearCitationMetadata() {self._citationMetadata = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _citationMetadata: Google_Ai_Generativelanguage_V1beta_CitationMetadata? = nil
}

/// Request to get a text embedding from the model.
struct Google_Ai_Generativelanguage_V1beta_EmbedTextRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The model name to use with the format model=models/{model}.
  var model: String = String()

  /// Optional. The free-form input text that the model will turn into an
  /// embedding.
  var text: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The response to a EmbedTextRequest.
struct Google_Ai_Generativelanguage_V1beta_EmbedTextResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Output only. The embedding generated from the input text.
  var embedding: Google_Ai_Generativelanguage_V1beta_Embedding {
    get {_embedding ?? Google_Ai_Generativelanguage_V1beta_Embedding()}
    set {_embedding = newValue}
  }
  /// Returns true if `embedding` has been explicitly set.
  var hasEmbedding: Bool {self._embedding != nil}
  /// Clears the value of `embedding`. Subsequent reads from it will return its default value.
  mutating func clearEmbedding() {self._embedding = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _embedding: Google_Ai_Generativelanguage_V1beta_Embedding? = nil
}

/// Batch request to get a text embedding from the model.
struct Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The name of the `Model` to use for generating the embedding.
  /// Examples:
  ///  models/embedding-gecko-001
  var model: String = String()

  /// Optional. The free-form input texts that the model will turn into an
  /// embedding. The current limit is 100 texts, over which an error will be
  /// thrown.
  var texts: [String] = []

  /// Optional. Embed requests for the batch. Only one of `texts` or `requests`
  /// can be set.
  var requests: [Google_Ai_Generativelanguage_V1beta_EmbedTextRequest] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// The response to a EmbedTextRequest.
struct Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Output only. The embeddings generated from the input text.
  var embeddings: [Google_Ai_Generativelanguage_V1beta_Embedding] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// A list of floats representing the embedding.
struct Google_Ai_Generativelanguage_V1beta_Embedding: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The embedding values.
  var value: [Float] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Counts the number of tokens in the `prompt` sent to a model.
///
/// Models may tokenize text differently, so each model may return a different
/// `token_count`.
struct Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Required. The model's resource name. This serves as an ID for the Model to
  /// use.
  ///
  /// This name should match a model name returned by the `ListModels` method.
  ///
  /// Format: `models/{model}`
  var model: String = String()

  /// Required. The free-form input text given to the model as a prompt.
  var prompt: Google_Ai_Generativelanguage_V1beta_TextPrompt {
    get {_prompt ?? Google_Ai_Generativelanguage_V1beta_TextPrompt()}
    set {_prompt = newValue}
  }
  /// Returns true if `prompt` has been explicitly set.
  var hasPrompt: Bool {self._prompt != nil}
  /// Clears the value of `prompt`. Subsequent reads from it will return its default value.
  mutating func clearPrompt() {self._prompt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _prompt: Google_Ai_Generativelanguage_V1beta_TextPrompt? = nil
}

/// A response from `CountTextTokens`.
///
/// It returns the model's `token_count` for the `prompt`.
struct Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The number of tokens that the `model` tokenizes the `prompt` into.
  ///
  /// Always non-negative.
  var tokenCount: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "google.ai.generativelanguage.v1beta"

extension Google_Ai_Generativelanguage_V1beta_GenerateTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GenerateTextRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}prompt\0\u{1}temperature\0\u{3}candidate_count\0\u{3}max_output_tokens\0\u{3}top_p\0\u{3}top_k\0\u{3}safety_settings\0\u{3}stop_sequences\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._prompt) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self._temperature) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._candidateCount) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._maxOutputTokens) }()
      case 6: try { try decoder.decodeSingularFloatField(value: &self._topP) }()
      case 7: try { try decoder.decodeSingularInt32Field(value: &self._topK) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.safetySettings) }()
      case 9: try { try decoder.decodeRepeatedStringField(value: &self.stopSequences) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    try { if let v = self._prompt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._temperature {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._candidateCount {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._maxOutputTokens {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._topP {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._topK {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 7)
    } }()
    if !self.safetySettings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.safetySettings, fieldNumber: 8)
    }
    if !self.stopSequences.isEmpty {
      try visitor.visitRepeatedStringField(value: self.stopSequences, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_GenerateTextRequest, rhs: Google_Ai_Generativelanguage_V1beta_GenerateTextRequest) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs._temperature != rhs._temperature {return false}
    if lhs._candidateCount != rhs._candidateCount {return false}
    if lhs._maxOutputTokens != rhs._maxOutputTokens {return false}
    if lhs._topP != rhs._topP {return false}
    if lhs._topK != rhs._topK {return false}
    if lhs.safetySettings != rhs.safetySettings {return false}
    if lhs.stopSequences != rhs.stopSequences {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_GenerateTextResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".GenerateTextResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}candidates\0\u{2}\u{2}filters\0\u{3}safety_feedback\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.candidates) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.filters) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.safetyFeedback) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.candidates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.candidates, fieldNumber: 1)
    }
    if !self.filters.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.filters, fieldNumber: 3)
    }
    if !self.safetyFeedback.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.safetyFeedback, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_GenerateTextResponse, rhs: Google_Ai_Generativelanguage_V1beta_GenerateTextResponse) -> Bool {
    if lhs.candidates != rhs.candidates {return false}
    if lhs.filters != rhs.filters {return false}
    if lhs.safetyFeedback != rhs.safetyFeedback {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_TextPrompt: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TextPrompt"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_TextPrompt, rhs: Google_Ai_Generativelanguage_V1beta_TextPrompt) -> Bool {
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_TextCompletion: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".TextCompletion"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}output\0\u{3}safety_ratings\0\u{3}citation_metadata\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.output) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.safetyRatings) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._citationMetadata) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.output.isEmpty {
      try visitor.visitSingularStringField(value: self.output, fieldNumber: 1)
    }
    if !self.safetyRatings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.safetyRatings, fieldNumber: 2)
    }
    try { if let v = self._citationMetadata {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_TextCompletion, rhs: Google_Ai_Generativelanguage_V1beta_TextCompletion) -> Bool {
    if lhs.output != rhs.output {return false}
    if lhs.safetyRatings != rhs.safetyRatings {return false}
    if lhs._citationMetadata != rhs._citationMetadata {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_EmbedTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EmbedTextRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}text\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.text) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    if !self.text.isEmpty {
      try visitor.visitSingularStringField(value: self.text, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_EmbedTextRequest, rhs: Google_Ai_Generativelanguage_V1beta_EmbedTextRequest) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.text != rhs.text {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_EmbedTextResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".EmbedTextResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}embedding\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._embedding) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._embedding {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_EmbedTextResponse, rhs: Google_Ai_Generativelanguage_V1beta_EmbedTextResponse) -> Bool {
    if lhs._embedding != rhs._embedding {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BatchEmbedTextRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}texts\0\u{1}requests\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.texts) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.requests) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    if !self.texts.isEmpty {
      try visitor.visitRepeatedStringField(value: self.texts, fieldNumber: 2)
    }
    if !self.requests.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.requests, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest, rhs: Google_Ai_Generativelanguage_V1beta_BatchEmbedTextRequest) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs.texts != rhs.texts {return false}
    if lhs.requests != rhs.requests {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".BatchEmbedTextResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}embeddings\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.embeddings) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.embeddings.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.embeddings, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse, rhs: Google_Ai_Generativelanguage_V1beta_BatchEmbedTextResponse) -> Bool {
    if lhs.embeddings != rhs.embeddings {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_Embedding: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Embedding"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedFloatField(value: &self.value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitPackedFloatField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_Embedding, rhs: Google_Ai_Generativelanguage_V1beta_Embedding) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CountTextTokensRequest"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}model\0\u{1}prompt\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.model) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._prompt) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.model.isEmpty {
      try visitor.visitSingularStringField(value: self.model, fieldNumber: 1)
    }
    try { if let v = self._prompt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest, rhs: Google_Ai_Generativelanguage_V1beta_CountTextTokensRequest) -> Bool {
    if lhs.model != rhs.model {return false}
    if lhs._prompt != rhs._prompt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CountTextTokensResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}token_count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.tokenCount) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.tokenCount != 0 {
      try visitor.visitSingularInt32Field(value: self.tokenCount, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse, rhs: Google_Ai_Generativelanguage_V1beta_CountTextTokensResponse) -> Bool {
    if lhs.tokenCount != rhs.tokenCount {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
