//
//  Content.swift
//  swift-gpt
//
//  Created by AFuture on 2025/7/21.
//

// MARK: Content - Text

extension GeneratedContentType {
    /// The content type for text-based responses.
    public static let text = GeneratedContentType(rawValue: "response.message.text")
}

/// Represents text content generated by an LLM.
public struct TextContent: PartialUpdatable, GeneratedItem, Codable {
    // TODO: Support content index
    
    public let type: GeneratedContentType = .text
    
    /// The partial update for the text content, used in streaming.
    public let delta: String?
    
    /// The complete text content, available in non-streaming or final stream events.
    public let content: String?
    /// Any annotations associated with the text content.
    public let annotations: [Annotation]
    
    enum CodingKeys: CodingKey {
        case type
        case delta
        case content
        case annotations
    }

    public init(delta: String?, content: String?, annotations: [Annotation]) {
        self.delta = delta
        self.content = content
        self.annotations = annotations
    }
}

// MARK: Content - Text Annotation

extension GeneratedContentType {
    static let textAnnotation = GeneratedContentType(rawValue: "response.message.text.annotation")
}

extension TextContent {
    /// Represents an annotation within a text content block.
    public struct Annotation: GeneratedItem, Codable {
        public let id: String
        public let type: GeneratedContentType = .textAnnotation
        
        /// The content of the annotation.
        public let content: String?
        
        enum CodingKeys: CodingKey {
            case id
            case type
            case content
        }

        public init(id: String, content: String?) {
            self.id = id
            self.content = content
        }
    }
}

// MARK: Content - Refusal

extension GeneratedContentType {
    /// The content type for a refusal to answer.
    static let textRefusal = GeneratedContentType(rawValue: "response.message.text.refusal")
}

/// Represents a refusal from the LLM to provide a response.
public struct TextRefusalContent: GeneratedItem, Codable {
    
    public let type: GeneratedContentType = .textRefusal
    
    /// The reason for the refusal.
    public let content: String?
    
    enum CodingKeys: CodingKey {
        case type
        case content
    }

    public init(content: String?) {
        self.content = content
    }
}

// MARK: Message

extension GeneratedContentType {
    /// The content type for a message item.
    public static let message = GeneratedContentType(rawValue: "response.message")
}

/// A single message item in a response, which can contain multiple content blocks.
public struct MessageItem: Identifiable, GeneratedSortableItem, Codable {
    public let id: String
    public let type: GeneratedContentType = .message
    public let index: Int?
    
    /// The content of the message, which can be text or a refusal.
    public let content: [ResponseContent]?
    
    enum CodingKeys: CodingKey {
        case id
        case type
        case index
        case content
    }

    public init(id: String, index: Int?, content: [ResponseContent]?) {
        self.id = id
        self.index = index
        self.content = content
    }
}
